# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import teams_pb2 as teams__pb2


class TeamsStub(object):
    """The teams service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTeam = channel.unary_unary(
                '/Teams/GetTeam',
                request_serializer=teams__pb2.TeamRequest.SerializeToString,
                response_deserializer=teams__pb2.TeamResponse.FromString,
                )


class TeamsServicer(object):
    """The teams service definition.
    """

    def GetTeam(self, request, context):
        """Returns the city and nickname of a team based on a string from the client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeamsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeam,
                    request_deserializer=teams__pb2.TeamRequest.FromString,
                    response_serializer=teams__pb2.TeamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Teams', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Teams(object):
    """The teams service definition.
    """

    @staticmethod
    def GetTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Teams/GetTeam',
            teams__pb2.TeamRequest.SerializeToString,
            teams__pb2.TeamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
