# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10my_service.proto\"\x1c\n\tMyRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\nMyResponse\x12\x10\n\x08response\x18\x01 \x01(\t2<\n\tMyService\x12/\n\x0eStreamMessages\x12\n.MyRequest\x1a\x0b.MyResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MYREQUEST._serialized_start=20
  _MYREQUEST._serialized_end=48
  _MYRESPONSE._serialized_start=50
  _MYRESPONSE._serialized_end=80
  _MYSERVICE._serialized_start=82
  _MYSERVICE._serialized_end=142
# @@protoc_insertion_point(module_scope)
